# Generated by Django 2.1.5 on 2019-01-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190122_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='Score',
            new_name='score',
        ),
    ]
