# Generated by Django 2.1.5 on 2019-01-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190122_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
